# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LIT-snapAndChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LIT-snapAndChat

pod "SwiftyCam"
pod 'Firebase/Core'
pod 'FirebaseDatabase'
pod 'FirebaseStorage'
pod 'FirebaseAuth'
pod "TextFieldEffects"

  target 'LIT-snapAndChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
