# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Voices' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Voices
pod "Pulsator"
pod 'NVActivityIndicatorView' 
pod 'Fabric'
pod 'Crashlytics'
 target 'VoicesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
