# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LIT-socialMedia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LIT-socialMedia


  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'SwiftKeychainWrapper'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  
  target 'LIT-socialMediaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LIT-socialMediaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
